#!/usr/bin/env php
<?php

// Load composer.
require_once(__DIR__ . '/src/Composer.php');
if (!\CoRex\Console\Composer::found()) {
    die('Composer vendor autoload.php not found.');
}
\CoRex\Console\Composer::load();

try {
    $artisan = new \CoRex\Console\Artisan();
    $artisan->addCommandsOnPath(__DIR__ . '/Commands');
    $artisan->execute();
} catch (Exception $e) {
    print($e->getMessage() . "\n");
}
